version: '3.8'
services:
  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ev-data-analytics-marketplace
      - MYSQL_ROOT_PASSWORD=123456
    command: --max_allowed_packet=64M
    ports:
      - '3307:3306'
    expose:
      - 3306  

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    
  ngnix:
    image: nginx:1.23.3
    ports:
      - 3000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p ev-data-analytics-marketplace up -d