version: '3.8'
services:
  ngnix:
    build:
      context: .
    ports:
      - 3000:80
    volumes:
      - ../../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # docker compose -p ev-data-analytics-marketplace-client up -d